/* soapClient.c
   Generated by gSOAP 2.8.22 from ims.h

Copyright(C) 2000-2015, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.8.22 2015-12-13 14:15:36 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call_psdims__user_register(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct psdims__register_info *user_info, int *ERRCODE)
{	struct psdims__user_register soap_tmp_psdims__user_register;
	struct psdims__user_registerResponse *soap_tmp_psdims__user_registerResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:10000";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp_psdims__user_register.user_info = user_info;
	soap_serializeheader(soap);
	soap_serialize_psdims__user_register(soap, &soap_tmp_psdims__user_register);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_psdims__user_register(soap, &soap_tmp_psdims__user_register, "psdims:user-register", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_psdims__user_register(soap, &soap_tmp_psdims__user_register, "psdims:user-register", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ERRCODE)
		return soap_closesock(soap);
	soap_default_int(soap, ERRCODE);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_psdims__user_registerResponse = soap_get_psdims__user_registerResponse(soap, NULL, "psdims:user-registerResponse", NULL);
	if (!soap_tmp_psdims__user_registerResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (ERRCODE && soap_tmp_psdims__user_registerResponse->ERRCODE)
		*ERRCODE = *soap_tmp_psdims__user_registerResponse->ERRCODE;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_psdims__user_unregister(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct psdims__login_info *login, int *ERRCODE)
{	struct psdims__user_unregister soap_tmp_psdims__user_unregister;
	struct psdims__user_unregisterResponse *soap_tmp_psdims__user_unregisterResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:10000";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp_psdims__user_unregister.login = login;
	soap_serializeheader(soap);
	soap_serialize_psdims__user_unregister(soap, &soap_tmp_psdims__user_unregister);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_psdims__user_unregister(soap, &soap_tmp_psdims__user_unregister, "psdims:user-unregister", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_psdims__user_unregister(soap, &soap_tmp_psdims__user_unregister, "psdims:user-unregister", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ERRCODE)
		return soap_closesock(soap);
	soap_default_int(soap, ERRCODE);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_psdims__user_unregisterResponse = soap_get_psdims__user_unregisterResponse(soap, NULL, "psdims:user-unregisterResponse", NULL);
	if (!soap_tmp_psdims__user_unregisterResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (ERRCODE && soap_tmp_psdims__user_unregisterResponse->ERRCODE)
		*ERRCODE = *soap_tmp_psdims__user_unregisterResponse->ERRCODE;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_psdims__get_user(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct psdims__login_info *login, struct psdims__user_info *user)
{	struct psdims__get_user soap_tmp_psdims__get_user;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:10000";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp_psdims__get_user.login = login;
	soap_serializeheader(soap);
	soap_serialize_psdims__get_user(soap, &soap_tmp_psdims__get_user);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_psdims__get_user(soap, &soap_tmp_psdims__get_user, "psdims:get-user", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_psdims__get_user(soap, &soap_tmp_psdims__get_user, "psdims:get-user", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!user)
		return soap_closesock(soap);
	soap_default_psdims__user_info(soap, user);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_psdims__user_info(soap, user, "psdims:user-info", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_psdims__get_friends(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct psdims__login_info *login, int timestamp, struct psdims__user_list *friends)
{	struct psdims__get_friends soap_tmp_psdims__get_friends;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:10000";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp_psdims__get_friends.login = login;
	soap_tmp_psdims__get_friends.timestamp = timestamp;
	soap_serializeheader(soap);
	soap_serialize_psdims__get_friends(soap, &soap_tmp_psdims__get_friends);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_psdims__get_friends(soap, &soap_tmp_psdims__get_friends, "psdims:get-friends", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_psdims__get_friends(soap, &soap_tmp_psdims__get_friends, "psdims:get-friends", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!friends)
		return soap_closesock(soap);
	soap_default_psdims__user_list(soap, friends);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_psdims__user_list(soap, friends, "psdims:user-list", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_psdims__get_chats(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct psdims__login_info *login, int timestamp, struct psdims__chat_list *chats)
{	struct psdims__get_chats soap_tmp_psdims__get_chats;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:10000";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp_psdims__get_chats.login = login;
	soap_tmp_psdims__get_chats.timestamp = timestamp;
	soap_serializeheader(soap);
	soap_serialize_psdims__get_chats(soap, &soap_tmp_psdims__get_chats);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_psdims__get_chats(soap, &soap_tmp_psdims__get_chats, "psdims:get-chats", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_psdims__get_chats(soap, &soap_tmp_psdims__get_chats, "psdims:get-chats", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!chats)
		return soap_closesock(soap);
	soap_default_psdims__chat_list(soap, chats);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_psdims__chat_list(soap, chats, "psdims:chat-list", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_psdims__get_chat_info(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct psdims__login_info *login, int chat_id, struct psdims__chat_info *chat)
{	struct psdims__get_chat_info soap_tmp_psdims__get_chat_info;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:10000";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp_psdims__get_chat_info.login = login;
	soap_tmp_psdims__get_chat_info.chat_id = chat_id;
	soap_serializeheader(soap);
	soap_serialize_psdims__get_chat_info(soap, &soap_tmp_psdims__get_chat_info);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_psdims__get_chat_info(soap, &soap_tmp_psdims__get_chat_info, "psdims:get-chat-info", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_psdims__get_chat_info(soap, &soap_tmp_psdims__get_chat_info, "psdims:get-chat-info", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!chat)
		return soap_closesock(soap);
	soap_default_psdims__chat_info(soap, chat);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_psdims__chat_info(soap, chat, "psdims:chat-info", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_psdims__get_chat_messages(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct psdims__login_info *login, int chat_id, int timestamp, struct psdims__message_list *messages)
{	struct psdims__get_chat_messages soap_tmp_psdims__get_chat_messages;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:10000";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp_psdims__get_chat_messages.login = login;
	soap_tmp_psdims__get_chat_messages.chat_id = chat_id;
	soap_tmp_psdims__get_chat_messages.timestamp = timestamp;
	soap_serializeheader(soap);
	soap_serialize_psdims__get_chat_messages(soap, &soap_tmp_psdims__get_chat_messages);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_psdims__get_chat_messages(soap, &soap_tmp_psdims__get_chat_messages, "psdims:get-chat-messages", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_psdims__get_chat_messages(soap, &soap_tmp_psdims__get_chat_messages, "psdims:get-chat-messages", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!messages)
		return soap_closesock(soap);
	soap_default_psdims__message_list(soap, messages);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_psdims__message_list(soap, messages, "psdims:message-list", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_psdims__get_attachment(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct psdims__login_info *login, int chat_id, int msg_timestamp, struct psdims__file *file)
{	struct psdims__get_attachment soap_tmp_psdims__get_attachment;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:10000";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp_psdims__get_attachment.login = login;
	soap_tmp_psdims__get_attachment.chat_id = chat_id;
	soap_tmp_psdims__get_attachment.msg_timestamp = msg_timestamp;
	soap_serializeheader(soap);
	soap_serialize_psdims__get_attachment(soap, &soap_tmp_psdims__get_attachment);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_psdims__get_attachment(soap, &soap_tmp_psdims__get_attachment, "psdims:get-attachment", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_psdims__get_attachment(soap, &soap_tmp_psdims__get_attachment, "psdims:get-attachment", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!file)
		return soap_closesock(soap);
	soap_default_psdims__file(soap, file);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_psdims__file(soap, file, "psdims:file", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_psdims__get_pending_notifications(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct psdims__login_info *login, int timestamp, struct psdims__notifications *notifications)
{	struct psdims__get_pending_notifications soap_tmp_psdims__get_pending_notifications;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:10000";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp_psdims__get_pending_notifications.login = login;
	soap_tmp_psdims__get_pending_notifications.timestamp = timestamp;
	soap_serializeheader(soap);
	soap_serialize_psdims__get_pending_notifications(soap, &soap_tmp_psdims__get_pending_notifications);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_psdims__get_pending_notifications(soap, &soap_tmp_psdims__get_pending_notifications, "psdims:get-pending-notifications", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_psdims__get_pending_notifications(soap, &soap_tmp_psdims__get_pending_notifications, "psdims:get-pending-notifications", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!notifications)
		return soap_closesock(soap);
	soap_default_psdims__notifications(soap, notifications);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_psdims__notifications(soap, notifications, "psdims:notifications", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_psdims__create_chat(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct psdims__login_info *login, struct psdims__new_chat *new_chat, int *chat_id)
{	struct psdims__create_chat soap_tmp_psdims__create_chat;
	struct psdims__create_chatResponse *soap_tmp_psdims__create_chatResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:10000";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp_psdims__create_chat.login = login;
	soap_tmp_psdims__create_chat.new_chat = new_chat;
	soap_serializeheader(soap);
	soap_serialize_psdims__create_chat(soap, &soap_tmp_psdims__create_chat);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_psdims__create_chat(soap, &soap_tmp_psdims__create_chat, "psdims:create-chat", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_psdims__create_chat(soap, &soap_tmp_psdims__create_chat, "psdims:create-chat", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!chat_id)
		return soap_closesock(soap);
	soap_default_int(soap, chat_id);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_psdims__create_chatResponse = soap_get_psdims__create_chatResponse(soap, NULL, "psdims:create-chatResponse", NULL);
	if (!soap_tmp_psdims__create_chatResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (chat_id && soap_tmp_psdims__create_chatResponse->chat_id)
		*chat_id = *soap_tmp_psdims__create_chatResponse->chat_id;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_psdims__add_member(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct psdims__login_info *login, char *name, int chat_id, int *ERRCODE)
{	struct psdims__add_member soap_tmp_psdims__add_member;
	struct psdims__add_memberResponse *soap_tmp_psdims__add_memberResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:10000";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp_psdims__add_member.login = login;
	soap_tmp_psdims__add_member.name = name;
	soap_tmp_psdims__add_member.chat_id = chat_id;
	soap_serializeheader(soap);
	soap_serialize_psdims__add_member(soap, &soap_tmp_psdims__add_member);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_psdims__add_member(soap, &soap_tmp_psdims__add_member, "psdims:add-member", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_psdims__add_member(soap, &soap_tmp_psdims__add_member, "psdims:add-member", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ERRCODE)
		return soap_closesock(soap);
	soap_default_int(soap, ERRCODE);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_psdims__add_memberResponse = soap_get_psdims__add_memberResponse(soap, NULL, "psdims:add-memberResponse", NULL);
	if (!soap_tmp_psdims__add_memberResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (ERRCODE && soap_tmp_psdims__add_memberResponse->ERRCODE)
		*ERRCODE = *soap_tmp_psdims__add_memberResponse->ERRCODE;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_psdims__quit_from_chat(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct psdims__login_info *login, int chat_id, int *ERRCODE)
{	struct psdims__quit_from_chat soap_tmp_psdims__quit_from_chat;
	struct psdims__quit_from_chatResponse *soap_tmp_psdims__quit_from_chatResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:10000";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp_psdims__quit_from_chat.login = login;
	soap_tmp_psdims__quit_from_chat.chat_id = chat_id;
	soap_serializeheader(soap);
	soap_serialize_psdims__quit_from_chat(soap, &soap_tmp_psdims__quit_from_chat);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_psdims__quit_from_chat(soap, &soap_tmp_psdims__quit_from_chat, "psdims:quit-from-chat", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_psdims__quit_from_chat(soap, &soap_tmp_psdims__quit_from_chat, "psdims:quit-from-chat", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ERRCODE)
		return soap_closesock(soap);
	soap_default_int(soap, ERRCODE);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_psdims__quit_from_chatResponse = soap_get_psdims__quit_from_chatResponse(soap, NULL, "psdims:quit-from-chatResponse", NULL);
	if (!soap_tmp_psdims__quit_from_chatResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (ERRCODE && soap_tmp_psdims__quit_from_chatResponse->ERRCODE)
		*ERRCODE = *soap_tmp_psdims__quit_from_chatResponse->ERRCODE;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_psdims__send_message(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct psdims__login_info *login, int chat_id, struct psdims__message_info *message, int *timestamp)
{	struct psdims__send_message soap_tmp_psdims__send_message;
	struct psdims__send_messageResponse *soap_tmp_psdims__send_messageResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:10000";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp_psdims__send_message.login = login;
	soap_tmp_psdims__send_message.chat_id = chat_id;
	soap_tmp_psdims__send_message.message = message;
	soap_serializeheader(soap);
	soap_serialize_psdims__send_message(soap, &soap_tmp_psdims__send_message);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_psdims__send_message(soap, &soap_tmp_psdims__send_message, "psdims:send-message", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_psdims__send_message(soap, &soap_tmp_psdims__send_message, "psdims:send-message", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!timestamp)
		return soap_closesock(soap);
	soap_default_int(soap, timestamp);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_psdims__send_messageResponse = soap_get_psdims__send_messageResponse(soap, NULL, "psdims:send-messageResponse", NULL);
	if (!soap_tmp_psdims__send_messageResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (timestamp && soap_tmp_psdims__send_messageResponse->timestamp)
		*timestamp = *soap_tmp_psdims__send_messageResponse->timestamp;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_psdims__send_attachment(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct psdims__login_info *login, int chat_id, int msg_timestamp, struct psdims__file *file, int *ERRCODE)
{	struct psdims__send_attachment soap_tmp_psdims__send_attachment;
	struct psdims__send_attachmentResponse *soap_tmp_psdims__send_attachmentResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:10000";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp_psdims__send_attachment.login = login;
	soap_tmp_psdims__send_attachment.chat_id = chat_id;
	soap_tmp_psdims__send_attachment.msg_timestamp = msg_timestamp;
	soap_tmp_psdims__send_attachment.file = file;
	soap_serializeheader(soap);
	soap_serialize_psdims__send_attachment(soap, &soap_tmp_psdims__send_attachment);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_psdims__send_attachment(soap, &soap_tmp_psdims__send_attachment, "psdims:send-attachment", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_psdims__send_attachment(soap, &soap_tmp_psdims__send_attachment, "psdims:send-attachment", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ERRCODE)
		return soap_closesock(soap);
	soap_default_int(soap, ERRCODE);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_psdims__send_attachmentResponse = soap_get_psdims__send_attachmentResponse(soap, NULL, "psdims:send-attachmentResponse", NULL);
	if (!soap_tmp_psdims__send_attachmentResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (ERRCODE && soap_tmp_psdims__send_attachmentResponse->ERRCODE)
		*ERRCODE = *soap_tmp_psdims__send_attachmentResponse->ERRCODE;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_psdims__send_friend_request(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct psdims__login_info *login, char *request_name, int *timestamp)
{	struct psdims__send_friend_request soap_tmp_psdims__send_friend_request;
	struct psdims__send_friend_requestResponse *soap_tmp_psdims__send_friend_requestResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:10000";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp_psdims__send_friend_request.login = login;
	soap_tmp_psdims__send_friend_request.request_name = request_name;
	soap_serializeheader(soap);
	soap_serialize_psdims__send_friend_request(soap, &soap_tmp_psdims__send_friend_request);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_psdims__send_friend_request(soap, &soap_tmp_psdims__send_friend_request, "psdims:send-friend-request", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_psdims__send_friend_request(soap, &soap_tmp_psdims__send_friend_request, "psdims:send-friend-request", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!timestamp)
		return soap_closesock(soap);
	soap_default_int(soap, timestamp);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_psdims__send_friend_requestResponse = soap_get_psdims__send_friend_requestResponse(soap, NULL, "psdims:send-friend-requestResponse", NULL);
	if (!soap_tmp_psdims__send_friend_requestResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (timestamp && soap_tmp_psdims__send_friend_requestResponse->timestamp)
		*timestamp = *soap_tmp_psdims__send_friend_requestResponse->timestamp;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_psdims__accept_request(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct psdims__login_info *login, char *request_name, int *timestamp)
{	struct psdims__accept_request soap_tmp_psdims__accept_request;
	struct psdims__accept_requestResponse *soap_tmp_psdims__accept_requestResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:10000";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp_psdims__accept_request.login = login;
	soap_tmp_psdims__accept_request.request_name = request_name;
	soap_serializeheader(soap);
	soap_serialize_psdims__accept_request(soap, &soap_tmp_psdims__accept_request);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_psdims__accept_request(soap, &soap_tmp_psdims__accept_request, "psdims:accept-request", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_psdims__accept_request(soap, &soap_tmp_psdims__accept_request, "psdims:accept-request", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!timestamp)
		return soap_closesock(soap);
	soap_default_int(soap, timestamp);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_psdims__accept_requestResponse = soap_get_psdims__accept_requestResponse(soap, NULL, "psdims:accept-requestResponse", NULL);
	if (!soap_tmp_psdims__accept_requestResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (timestamp && soap_tmp_psdims__accept_requestResponse->timestamp)
		*timestamp = *soap_tmp_psdims__accept_requestResponse->timestamp;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_psdims__decline_request(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct psdims__login_info *login, char *request_name, int *timestamp)
{	struct psdims__decline_request soap_tmp_psdims__decline_request;
	struct psdims__decline_requestResponse *soap_tmp_psdims__decline_requestResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:10000";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp_psdims__decline_request.login = login;
	soap_tmp_psdims__decline_request.request_name = request_name;
	soap_serializeheader(soap);
	soap_serialize_psdims__decline_request(soap, &soap_tmp_psdims__decline_request);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_psdims__decline_request(soap, &soap_tmp_psdims__decline_request, "psdims:decline-request", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_psdims__decline_request(soap, &soap_tmp_psdims__decline_request, "psdims:decline-request", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!timestamp)
		return soap_closesock(soap);
	soap_default_int(soap, timestamp);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp_psdims__decline_requestResponse = soap_get_psdims__decline_requestResponse(soap, NULL, "psdims:decline-requestResponse", NULL);
	if (!soap_tmp_psdims__decline_requestResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (timestamp && soap_tmp_psdims__decline_requestResponse->timestamp)
		*timestamp = *soap_tmp_psdims__decline_requestResponse->timestamp;
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.c */
