/* soapServer.c
   Generated by gSOAP 2.8.22 from ims.h

Copyright(C) 2000-2015, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapServer.c ver 2.8.22 2015-12-13 14:15:36 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif
	do
	{
#ifndef WITH_FASTCGI
		if (soap->max_keep_alive > 0 && !--k)
			soap->keep_alive = 0;
#endif
		if (soap_begin_serve(soap))
		{	if (soap->error >= SOAP_STOP)
				continue;
			return soap->error;
		}
		if (soap_serve_request(soap) || (soap->fserveloop && soap->fserveloop(soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "psdims:user-register"))
		return soap_serve_psdims__user_register(soap);
	if (!soap_match_tag(soap, soap->tag, "psdims:user-unregister"))
		return soap_serve_psdims__user_unregister(soap);
	if (!soap_match_tag(soap, soap->tag, "psdims:get-user"))
		return soap_serve_psdims__get_user(soap);
	if (!soap_match_tag(soap, soap->tag, "psdims:get-friends"))
		return soap_serve_psdims__get_friends(soap);
	if (!soap_match_tag(soap, soap->tag, "psdims:get-chats"))
		return soap_serve_psdims__get_chats(soap);
	if (!soap_match_tag(soap, soap->tag, "psdims:get-chat-info"))
		return soap_serve_psdims__get_chat_info(soap);
	if (!soap_match_tag(soap, soap->tag, "psdims:get-chat-messages"))
		return soap_serve_psdims__get_chat_messages(soap);
	if (!soap_match_tag(soap, soap->tag, "psdims:get-attachment"))
		return soap_serve_psdims__get_attachment(soap);
	if (!soap_match_tag(soap, soap->tag, "psdims:get-pending-notifications"))
		return soap_serve_psdims__get_pending_notifications(soap);
	if (!soap_match_tag(soap, soap->tag, "psdims:create-chat"))
		return soap_serve_psdims__create_chat(soap);
	if (!soap_match_tag(soap, soap->tag, "psdims:add-member"))
		return soap_serve_psdims__add_member(soap);
	if (!soap_match_tag(soap, soap->tag, "psdims:quit-from-chat"))
		return soap_serve_psdims__quit_from_chat(soap);
	if (!soap_match_tag(soap, soap->tag, "psdims:send-message"))
		return soap_serve_psdims__send_message(soap);
	if (!soap_match_tag(soap, soap->tag, "psdims:send-attachment"))
		return soap_serve_psdims__send_attachment(soap);
	if (!soap_match_tag(soap, soap->tag, "psdims:send-friend-request"))
		return soap_serve_psdims__send_friend_request(soap);
	if (!soap_match_tag(soap, soap->tag, "psdims:accept-request"))
		return soap_serve_psdims__accept_request(soap);
	if (!soap_match_tag(soap, soap->tag, "psdims:decline-request"))
		return soap_serve_psdims__decline_request(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_psdims__user_register(struct soap *soap)
{	struct psdims__user_register soap_tmp_psdims__user_register;
	struct psdims__user_registerResponse soap_tmp_psdims__user_registerResponse;
	int soap_tmp_int;
	soap_default_psdims__user_registerResponse(soap, &soap_tmp_psdims__user_registerResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_psdims__user_registerResponse.ERRCODE = &soap_tmp_int;
	soap_default_psdims__user_register(soap, &soap_tmp_psdims__user_register);
	if (!soap_get_psdims__user_register(soap, &soap_tmp_psdims__user_register, "psdims:user-register", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = psdims__user_register(soap, soap_tmp_psdims__user_register.user_info, soap_tmp_psdims__user_registerResponse.ERRCODE);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_psdims__user_registerResponse(soap, &soap_tmp_psdims__user_registerResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_psdims__user_registerResponse(soap, &soap_tmp_psdims__user_registerResponse, "psdims:user-registerResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_psdims__user_registerResponse(soap, &soap_tmp_psdims__user_registerResponse, "psdims:user-registerResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_psdims__user_unregister(struct soap *soap)
{	struct psdims__user_unregister soap_tmp_psdims__user_unregister;
	struct psdims__user_unregisterResponse soap_tmp_psdims__user_unregisterResponse;
	int soap_tmp_int;
	soap_default_psdims__user_unregisterResponse(soap, &soap_tmp_psdims__user_unregisterResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_psdims__user_unregisterResponse.ERRCODE = &soap_tmp_int;
	soap_default_psdims__user_unregister(soap, &soap_tmp_psdims__user_unregister);
	if (!soap_get_psdims__user_unregister(soap, &soap_tmp_psdims__user_unregister, "psdims:user-unregister", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = psdims__user_unregister(soap, soap_tmp_psdims__user_unregister.login, soap_tmp_psdims__user_unregisterResponse.ERRCODE);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_psdims__user_unregisterResponse(soap, &soap_tmp_psdims__user_unregisterResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_psdims__user_unregisterResponse(soap, &soap_tmp_psdims__user_unregisterResponse, "psdims:user-unregisterResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_psdims__user_unregisterResponse(soap, &soap_tmp_psdims__user_unregisterResponse, "psdims:user-unregisterResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_psdims__get_user(struct soap *soap)
{	struct psdims__get_user soap_tmp_psdims__get_user;
	struct psdims__user_info user;
	soap_default_psdims__user_info(soap, &user);
	soap_default_psdims__get_user(soap, &soap_tmp_psdims__get_user);
	if (!soap_get_psdims__get_user(soap, &soap_tmp_psdims__get_user, "psdims:get-user", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = psdims__get_user(soap, soap_tmp_psdims__get_user.login, &user);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_psdims__user_info(soap, &user);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_psdims__user_info(soap, &user, "psdims:user-info", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_psdims__user_info(soap, &user, "psdims:user-info", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_psdims__get_friends(struct soap *soap)
{	struct psdims__get_friends soap_tmp_psdims__get_friends;
	struct psdims__user_list friends;
	soap_default_psdims__user_list(soap, &friends);
	soap_default_psdims__get_friends(soap, &soap_tmp_psdims__get_friends);
	if (!soap_get_psdims__get_friends(soap, &soap_tmp_psdims__get_friends, "psdims:get-friends", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = psdims__get_friends(soap, soap_tmp_psdims__get_friends.login, soap_tmp_psdims__get_friends.timestamp, &friends);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_psdims__user_list(soap, &friends);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_psdims__user_list(soap, &friends, "psdims:user-list", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_psdims__user_list(soap, &friends, "psdims:user-list", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_psdims__get_chats(struct soap *soap)
{	struct psdims__get_chats soap_tmp_psdims__get_chats;
	struct psdims__chat_list chats;
	soap_default_psdims__chat_list(soap, &chats);
	soap_default_psdims__get_chats(soap, &soap_tmp_psdims__get_chats);
	if (!soap_get_psdims__get_chats(soap, &soap_tmp_psdims__get_chats, "psdims:get-chats", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = psdims__get_chats(soap, soap_tmp_psdims__get_chats.login, soap_tmp_psdims__get_chats.timestamp, &chats);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_psdims__chat_list(soap, &chats);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_psdims__chat_list(soap, &chats, "psdims:chat-list", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_psdims__chat_list(soap, &chats, "psdims:chat-list", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_psdims__get_chat_info(struct soap *soap)
{	struct psdims__get_chat_info soap_tmp_psdims__get_chat_info;
	struct psdims__chat_info chat;
	soap_default_psdims__chat_info(soap, &chat);
	soap_default_psdims__get_chat_info(soap, &soap_tmp_psdims__get_chat_info);
	if (!soap_get_psdims__get_chat_info(soap, &soap_tmp_psdims__get_chat_info, "psdims:get-chat-info", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = psdims__get_chat_info(soap, soap_tmp_psdims__get_chat_info.login, soap_tmp_psdims__get_chat_info.chat_id, &chat);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_psdims__chat_info(soap, &chat);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_psdims__chat_info(soap, &chat, "psdims:chat-info", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_psdims__chat_info(soap, &chat, "psdims:chat-info", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_psdims__get_chat_messages(struct soap *soap)
{	struct psdims__get_chat_messages soap_tmp_psdims__get_chat_messages;
	struct psdims__message_list messages;
	soap_default_psdims__message_list(soap, &messages);
	soap_default_psdims__get_chat_messages(soap, &soap_tmp_psdims__get_chat_messages);
	if (!soap_get_psdims__get_chat_messages(soap, &soap_tmp_psdims__get_chat_messages, "psdims:get-chat-messages", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = psdims__get_chat_messages(soap, soap_tmp_psdims__get_chat_messages.login, soap_tmp_psdims__get_chat_messages.chat_id, soap_tmp_psdims__get_chat_messages.timestamp, &messages);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_psdims__message_list(soap, &messages);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_psdims__message_list(soap, &messages, "psdims:message-list", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_psdims__message_list(soap, &messages, "psdims:message-list", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_psdims__get_attachment(struct soap *soap)
{	struct psdims__get_attachment soap_tmp_psdims__get_attachment;
	struct psdims__file file;
	soap_default_psdims__file(soap, &file);
	soap_default_psdims__get_attachment(soap, &soap_tmp_psdims__get_attachment);
	if (!soap_get_psdims__get_attachment(soap, &soap_tmp_psdims__get_attachment, "psdims:get-attachment", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = psdims__get_attachment(soap, soap_tmp_psdims__get_attachment.login, soap_tmp_psdims__get_attachment.chat_id, soap_tmp_psdims__get_attachment.msg_timestamp, &file);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_psdims__file(soap, &file);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_psdims__file(soap, &file, "psdims:file", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_psdims__file(soap, &file, "psdims:file", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_psdims__get_pending_notifications(struct soap *soap)
{	struct psdims__get_pending_notifications soap_tmp_psdims__get_pending_notifications;
	struct psdims__notifications notifications;
	soap_default_psdims__notifications(soap, &notifications);
	soap_default_psdims__get_pending_notifications(soap, &soap_tmp_psdims__get_pending_notifications);
	if (!soap_get_psdims__get_pending_notifications(soap, &soap_tmp_psdims__get_pending_notifications, "psdims:get-pending-notifications", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = psdims__get_pending_notifications(soap, soap_tmp_psdims__get_pending_notifications.login, soap_tmp_psdims__get_pending_notifications.timestamp, &notifications);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_psdims__notifications(soap, &notifications);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_psdims__notifications(soap, &notifications, "psdims:notifications", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_psdims__notifications(soap, &notifications, "psdims:notifications", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_psdims__create_chat(struct soap *soap)
{	struct psdims__create_chat soap_tmp_psdims__create_chat;
	struct psdims__create_chatResponse soap_tmp_psdims__create_chatResponse;
	int soap_tmp_int;
	soap_default_psdims__create_chatResponse(soap, &soap_tmp_psdims__create_chatResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_psdims__create_chatResponse.chat_id = &soap_tmp_int;
	soap_default_psdims__create_chat(soap, &soap_tmp_psdims__create_chat);
	if (!soap_get_psdims__create_chat(soap, &soap_tmp_psdims__create_chat, "psdims:create-chat", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = psdims__create_chat(soap, soap_tmp_psdims__create_chat.login, soap_tmp_psdims__create_chat.new_chat, soap_tmp_psdims__create_chatResponse.chat_id);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_psdims__create_chatResponse(soap, &soap_tmp_psdims__create_chatResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_psdims__create_chatResponse(soap, &soap_tmp_psdims__create_chatResponse, "psdims:create-chatResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_psdims__create_chatResponse(soap, &soap_tmp_psdims__create_chatResponse, "psdims:create-chatResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_psdims__add_member(struct soap *soap)
{	struct psdims__add_member soap_tmp_psdims__add_member;
	struct psdims__add_memberResponse soap_tmp_psdims__add_memberResponse;
	int soap_tmp_int;
	soap_default_psdims__add_memberResponse(soap, &soap_tmp_psdims__add_memberResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_psdims__add_memberResponse.ERRCODE = &soap_tmp_int;
	soap_default_psdims__add_member(soap, &soap_tmp_psdims__add_member);
	if (!soap_get_psdims__add_member(soap, &soap_tmp_psdims__add_member, "psdims:add-member", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = psdims__add_member(soap, soap_tmp_psdims__add_member.login, soap_tmp_psdims__add_member.name, soap_tmp_psdims__add_member.chat_id, soap_tmp_psdims__add_memberResponse.ERRCODE);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_psdims__add_memberResponse(soap, &soap_tmp_psdims__add_memberResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_psdims__add_memberResponse(soap, &soap_tmp_psdims__add_memberResponse, "psdims:add-memberResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_psdims__add_memberResponse(soap, &soap_tmp_psdims__add_memberResponse, "psdims:add-memberResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_psdims__quit_from_chat(struct soap *soap)
{	struct psdims__quit_from_chat soap_tmp_psdims__quit_from_chat;
	struct psdims__quit_from_chatResponse soap_tmp_psdims__quit_from_chatResponse;
	int soap_tmp_int;
	soap_default_psdims__quit_from_chatResponse(soap, &soap_tmp_psdims__quit_from_chatResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_psdims__quit_from_chatResponse.ERRCODE = &soap_tmp_int;
	soap_default_psdims__quit_from_chat(soap, &soap_tmp_psdims__quit_from_chat);
	if (!soap_get_psdims__quit_from_chat(soap, &soap_tmp_psdims__quit_from_chat, "psdims:quit-from-chat", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = psdims__quit_from_chat(soap, soap_tmp_psdims__quit_from_chat.login, soap_tmp_psdims__quit_from_chat.chat_id, soap_tmp_psdims__quit_from_chatResponse.ERRCODE);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_psdims__quit_from_chatResponse(soap, &soap_tmp_psdims__quit_from_chatResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_psdims__quit_from_chatResponse(soap, &soap_tmp_psdims__quit_from_chatResponse, "psdims:quit-from-chatResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_psdims__quit_from_chatResponse(soap, &soap_tmp_psdims__quit_from_chatResponse, "psdims:quit-from-chatResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_psdims__send_message(struct soap *soap)
{	struct psdims__send_message soap_tmp_psdims__send_message;
	struct psdims__send_messageResponse soap_tmp_psdims__send_messageResponse;
	int soap_tmp_int;
	soap_default_psdims__send_messageResponse(soap, &soap_tmp_psdims__send_messageResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_psdims__send_messageResponse.timestamp = &soap_tmp_int;
	soap_default_psdims__send_message(soap, &soap_tmp_psdims__send_message);
	if (!soap_get_psdims__send_message(soap, &soap_tmp_psdims__send_message, "psdims:send-message", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = psdims__send_message(soap, soap_tmp_psdims__send_message.login, soap_tmp_psdims__send_message.chat_id, soap_tmp_psdims__send_message.message, soap_tmp_psdims__send_messageResponse.timestamp);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_psdims__send_messageResponse(soap, &soap_tmp_psdims__send_messageResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_psdims__send_messageResponse(soap, &soap_tmp_psdims__send_messageResponse, "psdims:send-messageResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_psdims__send_messageResponse(soap, &soap_tmp_psdims__send_messageResponse, "psdims:send-messageResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_psdims__send_attachment(struct soap *soap)
{	struct psdims__send_attachment soap_tmp_psdims__send_attachment;
	struct psdims__send_attachmentResponse soap_tmp_psdims__send_attachmentResponse;
	int soap_tmp_int;
	soap_default_psdims__send_attachmentResponse(soap, &soap_tmp_psdims__send_attachmentResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_psdims__send_attachmentResponse.ERRCODE = &soap_tmp_int;
	soap_default_psdims__send_attachment(soap, &soap_tmp_psdims__send_attachment);
	if (!soap_get_psdims__send_attachment(soap, &soap_tmp_psdims__send_attachment, "psdims:send-attachment", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = psdims__send_attachment(soap, soap_tmp_psdims__send_attachment.login, soap_tmp_psdims__send_attachment.chat_id, soap_tmp_psdims__send_attachment.msg_timestamp, soap_tmp_psdims__send_attachment.file, soap_tmp_psdims__send_attachmentResponse.ERRCODE);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_psdims__send_attachmentResponse(soap, &soap_tmp_psdims__send_attachmentResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_psdims__send_attachmentResponse(soap, &soap_tmp_psdims__send_attachmentResponse, "psdims:send-attachmentResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_psdims__send_attachmentResponse(soap, &soap_tmp_psdims__send_attachmentResponse, "psdims:send-attachmentResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_psdims__send_friend_request(struct soap *soap)
{	struct psdims__send_friend_request soap_tmp_psdims__send_friend_request;
	struct psdims__send_friend_requestResponse soap_tmp_psdims__send_friend_requestResponse;
	int soap_tmp_int;
	soap_default_psdims__send_friend_requestResponse(soap, &soap_tmp_psdims__send_friend_requestResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_psdims__send_friend_requestResponse.timestamp = &soap_tmp_int;
	soap_default_psdims__send_friend_request(soap, &soap_tmp_psdims__send_friend_request);
	if (!soap_get_psdims__send_friend_request(soap, &soap_tmp_psdims__send_friend_request, "psdims:send-friend-request", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = psdims__send_friend_request(soap, soap_tmp_psdims__send_friend_request.login, soap_tmp_psdims__send_friend_request.request_name, soap_tmp_psdims__send_friend_requestResponse.timestamp);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_psdims__send_friend_requestResponse(soap, &soap_tmp_psdims__send_friend_requestResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_psdims__send_friend_requestResponse(soap, &soap_tmp_psdims__send_friend_requestResponse, "psdims:send-friend-requestResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_psdims__send_friend_requestResponse(soap, &soap_tmp_psdims__send_friend_requestResponse, "psdims:send-friend-requestResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_psdims__accept_request(struct soap *soap)
{	struct psdims__accept_request soap_tmp_psdims__accept_request;
	struct psdims__accept_requestResponse soap_tmp_psdims__accept_requestResponse;
	int soap_tmp_int;
	soap_default_psdims__accept_requestResponse(soap, &soap_tmp_psdims__accept_requestResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_psdims__accept_requestResponse.timestamp = &soap_tmp_int;
	soap_default_psdims__accept_request(soap, &soap_tmp_psdims__accept_request);
	if (!soap_get_psdims__accept_request(soap, &soap_tmp_psdims__accept_request, "psdims:accept-request", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = psdims__accept_request(soap, soap_tmp_psdims__accept_request.login, soap_tmp_psdims__accept_request.request_name, soap_tmp_psdims__accept_requestResponse.timestamp);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_psdims__accept_requestResponse(soap, &soap_tmp_psdims__accept_requestResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_psdims__accept_requestResponse(soap, &soap_tmp_psdims__accept_requestResponse, "psdims:accept-requestResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_psdims__accept_requestResponse(soap, &soap_tmp_psdims__accept_requestResponse, "psdims:accept-requestResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_psdims__decline_request(struct soap *soap)
{	struct psdims__decline_request soap_tmp_psdims__decline_request;
	struct psdims__decline_requestResponse soap_tmp_psdims__decline_requestResponse;
	int soap_tmp_int;
	soap_default_psdims__decline_requestResponse(soap, &soap_tmp_psdims__decline_requestResponse);
	soap_default_int(soap, &soap_tmp_int);
	soap_tmp_psdims__decline_requestResponse.timestamp = &soap_tmp_int;
	soap_default_psdims__decline_request(soap, &soap_tmp_psdims__decline_request);
	if (!soap_get_psdims__decline_request(soap, &soap_tmp_psdims__decline_request, "psdims:decline-request", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = psdims__decline_request(soap, soap_tmp_psdims__decline_request.login, soap_tmp_psdims__decline_request.request_name, soap_tmp_psdims__decline_requestResponse.timestamp);
	if (soap->error)
		return soap->error;
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize_psdims__decline_requestResponse(soap, &soap_tmp_psdims__decline_requestResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_psdims__decline_requestResponse(soap, &soap_tmp_psdims__decline_requestResponse, "psdims:decline-requestResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_psdims__decline_requestResponse(soap, &soap_tmp_psdims__decline_requestResponse, "psdims:decline-requestResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapServer.c */
