CREATE DATABASE PSD;

USE PSD;

CREATE TABLE users(
 ID INT NOT NULL,
 NAME VARCHAR(25) NOT NULL ,
 INFORMATION VARCHAR(100),
 PRIMARY KEY (ID)
);

CREATE TABLE chats(
 ID INT(10) NOT NULL,
 ID_ADMIN INT(10) NOT NULL,
 DECRIPTION VARCHAR(100),
 PRIMARY KEY(ID),
 FOREIGN KEY (ID_ADMIN) REFERENCES users(ID)
);

CREATE TABLE friends(
 ID1 INT(10) NOT NULL, 
 ID2 INT(10) NOT NULL,
 INFORMATION VARCHAR(100) ,
 FOREIGN KEY (ID1) REFERENCES users(ID),
 FOREIGN KEY (ID2) REFERENCES users(ID) 
);

CREATE TABLE users_chats(
 ID_USERS INT(10) NOT NULL, 
 ID_CHAT INT(10) NOT NULL,
 FOREIGN KEY (ID_USERS) REFERENCES users(ID),
 FOREIGN KEY (ID_CHAT) REFERENCES chats(ID) 
);

CREATE TABLE messages(
 ID_SENDER INT(10) NOT NULL, 
 ID_CHAT INT(10) NOT NULL,
 FILE_ INT(1) NOT NULL,
 TEXT VARCHAR(500) ,
 SEND_TIMESTAMP TIME,
 RECEIVE_TIMESTAMP TIME,
 FOREIGN KEY (ID_SENDER) REFERENCES users(ID),
 FOREIGN KEY (ID_CHAT) REFERENCES chats(ID) 
);



